devtools::setup(".", rstudio=FALSE)
devtools::use_testthat()
devtools::document()
devtools::use_package("httr")
devtools::use_package("jsonlite")
devtools::check(".")
devtools::build(".")
devtools::install(".")
